# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

# Le système utilisé pour build, pas la VM de destination !
pool:
  vmImage: ubuntu-latest

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '15.x'
#   displayName: 'INSTALL NODE.JS'

# - script: |
#     yarn install
#     yarn build
#   displayName: 'YARN INSTALL AND BUILD'
- script: echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
  displayName: Write build info
  workingDirectory: .

- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    contents: |
      **/*
      !.git/**/*
      !env/
    # Ce dossier est un dossier sur l'agent de build
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  # cett tâche rend disponible dans Azure Pipeline (dans le tableau de bord)
  # des artefacts ou des fichiers construits lors du build
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Movies App Files'
