# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Deploy
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
    - task: CopyFiles@2
      displayName: 'Copy files'
      inputs:
        sourceFolder: '$(Build.Repository.LocalPath)'
        contents: |
          **/*
          !.git/**/*
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
